---
# Get CSP tools location (needed for excel validation)
- name: Get CSP tools
  uri:
    url: http://{{ ob }}:8080/api/v1/excel/csptoolspath
    headers:
      Authorization: Bearer {{ token.json.access_token }}
      project-id: "{{ project_id['json'][0]['id'] }}"
  register: csp_tools_path
- name: Output CSP Tools path
  debug:
    var: csp_tools_path['json']
  tags: [ never, debug ]

# Excel upload (using Curl, because uri module does not support multipart/form-data content)
- name: Validate excel (using Curl)
  shell: |
    curl -s -o curl.raw -w "%{http_code}" -X POST \
    -H "Authorization:Bearer {{ token['json']['access_token'] }}" \
    -H "project-id:{{ project_id['json'][0]['id'] }}" \
    -H "Content-Type:multipart/form-data" \
    -H "cspToolPath:{{ csp_tools_path['json'] }}" \
    -H "vim-url:/api/v1/excel/validate" \
    -H "userName:{{ user }}" \
    -F "file=@\"{{ excel_file }}\";type=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;filename=\"onboarding.xlsx\"" \
    "http://{{ ob }}:8080/api/v1/excel/validate"
  args:
    warn: no
  register: validation_response
  failed_when: validation_response['stdout'] != "200"
- debug:
    var: validation_response
  tags: [ never, debug ]

# Get list of validated items from excel
- name: Select for onboard
  uri:
    url: http://{{ ob }}:8080/api/v1/excel/selectForOnboard
    headers:
      Authorization: Bearer {{ token['json']['access_token'] }}
      project-id: "{{ project_id['json'][0]['id'] }}"
  register: onboard_list
- name: Output excel list
  debug:
    var: onboard_list
  tags: [ never, debug ]
- name: For test
  copy:
    content: "{{ onboard_list }}"
    dest: onboard_list.raw
  tags: [ never, raw ]

