---
- name: Onboard excel
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - common
    - validate_excel

  tasks:
# Onboarding VIM

    # Read existing
    - name: List VIMs
      uri:
        url: http://{{ ob }}:8080/api/v1/datacenters
        headers:
          Authorization: Bearer {{ token['json']['access_token'] }}
          project-id: "{{ project_id['json'][0]['id'] }}"
      register: datacenters

    # VIM already existing
    - name: VIM already existing
      debug:
        msg: "Vim named {{ vim }} already exists"
      when: datacenters.json|selectattr('name', 'equalto', vim)|list|length>0

    # VIM not existing, register new
    - block:
        - name: Register VIM
          uri:
            url: http://{{ ob }}:8080/api/v1/excel/selectedvimonboard
            headers:
              Authorization: Bearer {{ token.json.access_token }}
              project-id: "{{ project_id['json'][0]['id'] }}"
              data: "{{ vim }}"
          register: vim_registration
        # Parse output for errors (status code is always 200)
        - fail:
            msg: "VIM registration failed: {{ vim_registration.json.report[1] }}"
          when: vim_registration.json.report[2] != 'ok'

        - name: Output VIM registration
          debug:
            var: vim_registration
          tags: [ never, debug ]
        - name: For offline test
          copy:
            content: "{{ vim_registration }}"
            dest: vim_registration.raw
          tags: [ never, raw ]
      when: datacenters.json|selectattr('name', 'equalto', vim)|list|length==0


# Onboarding NSDs
    - set_fact:
        all_onboarding_ok: true

    # Loop over all NSDs
    - include: includes/onboard_nsd.yaml
      with_items: "{{ onboard_list.json.report }}"
      when: item.split(';==;').pop(0)=='wModel items:'
      loop_control:
        label: "{{ item }}"

    # Aggregated status (errors during loop are ignored)
    - name: Success check
      fail:
        msg: "Some of the onboardings have failed!"
      when: not all_onboarding_ok
